services:
  metatrader:
    image: mt5
    container_name: mt5
    environment:
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./templates/:/home/mt5/program/MQL5/Profiles/Templates/
      - ./project/:/home/mt5/program/MQL5/Experts/