services:
  metatrader:
    image: p3ps1man/dockertrader-x11
    container_name: mt5
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - app:/home/mt5/program/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./templates/:/home/mt5/program/MQL5/Profiles/Templates/
      - ./project/:/home/mt5/program/MQL5/Experts/

volumes:
  app: